<?php
/**
 * Created by PhpStorm.
 * User: vladimirtunikov
 * Date: 16.05.16
 * Time: 11:57
 */

namespace App\Test\TestCase\Suite\HttpClientMockerTest;

use App\Lib\Client;
use App\Test\Suite\HttpClientMocker;
use App\Test\TestCase\AppTestCase;
use Cake\Http\Client\Request;
use Cake\Http\Client\Response;

class HttpClientMockerTest extends AppTestCase
{
	/**
	 * @inheritdoc
	 */
	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
		HttpClientMocker::clean();
	}

	/**
	 * Мок запроса
	 */
	public function testMock() {
		$url = 'http://www.artskills.ru';
		$method = Request::METHOD_POST;
		$post = ['foo' => 'bar'];
		$returnArray = [
			'arr' => 1,
			2 => 3,
		];

		$mock = HttpClientMocker::mock($url, $method);
		$mock->singleCall()
			->expectBody($post)
			->willReturnJson($returnArray);

		$client = new Client();
		$this->assertNotEmpty($client->get($url)->body);
		$this->assertEquals($returnArray, $client->post($url, $post)->json);
	}

	/**
	 * Тест снифера запросов
	 */
	public function testSynteticSniff() {
		$testArray = ['request' => 'request', 'response' => 'response'];

		HttpClientMocker::addSniff($testArray);

		$resultCollection = HttpClientMocker::getSniffList();
		$this->assertEquals(1, count($resultCollection));
		$this->assertEquals($testArray, $resultCollection[0]);

		HttpClientMocker::clean();
		$this->assertEquals(0, count(HttpClientMocker::getSniffList()));
	}

	/**
	 * Тесто полного цикла снифа
	 */
	public function testRealSniff() {
		$url = 'http://www.artskills.ru';
		$client = new Client();
		$clientResponse = $client->get($url);

		$sniffCollection = HttpClientMocker::getSniffList();
		$this->assertEquals(1, count($sniffCollection));
		/**
		 * @var Request $sniffRequest
		 */
		$sniffRequest = $sniffCollection[0]['request'];
		/**
		 * @var Response $sniffResponse
		 */
		$sniffResponse = $sniffCollection[0]['response'];
		$this->assertEquals($url, $sniffRequest->url());
		$this->assertEquals($clientResponse->body, $sniffResponse->body);
	}
}